# Generated by Django 4.2.11 on 2024-09-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_backed', '0010_alter_batterylivestatus_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatterySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devId', models.CharField(default='batt-0001', max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('invertor', models.FloatField(default=0)),
            ],
        ),
    ]
