# Generated by Django 4.2.11 on 2024-09-18 10:32

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('battery_backed', '0011_batteryschedule'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='batteryschedule',
            managers=[
                ('dam', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='batteryschedule',
            name='devId',
            field=models.CharField(default='batt1', max_length=20),
        ),
    ]
