# Generated by Django 4.2.11 on 2024-09-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_backed', '0012_alter_batteryschedule_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batteryschedule',
            name='flow',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='batteryschedule',
            name='soc',
            field=models.FloatField(default=0),
        ),
    ]
