# Generated by Django 4.2.11 on 2024-10-08 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battery_backed', '0013_batteryschedule_flow_batteryschedule_soc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batteryschedule',
            unique_together={('devId', 'timestamp')},
        ),
    ]
