# Generated by Django 4.2.11 on 2024-10-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_backed', '0014_alter_batteryschedule_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearAgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devId', models.CharField(default='batt-0001', max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('state_of_charge', models.FloatField(default=0)),
                ('flow_last_min', models.FloatField(default=0)),
                ('invertor_power', models.FloatField(default=0)),
            ],
            options={
                'unique_together': {('devId', 'timestamp')},
            },
        ),
    ]
