# Generated by Django 4.2.11 on 2024-10-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_backed', '0015_yearagg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devId', models.CharField(default='batt-0001', max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('cumulative_soc', models.FloatField(default=0)),
                ('cumulative_flow_last_min', models.FloatField(default=0)),
                ('cumulative_invertor_power', models.FloatField(default=0)),
            ],
            options={
                'unique_together': {('devId', 'timestamp')},
            },
        ),
    ]
