# Generated by Django 4.2.11 on 2024-10-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battery_backed', '0016_cumulativeyear'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cumulativeyear',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cumulativeyear',
            name='devId',
        ),
    ]
