# Generated by Django 4.2.11 on 2025-05-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_backed', '0019_forecastedprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteryschedule',
            name='flow',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='batteryschedule',
            name='invertor',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='batteryschedule',
            name='soc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
