# Generated by Django 4.2.11 on 2025-12-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery_backed', '0020_alter_batteryschedule_flow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteryschedule',
            name='devId',
            field=models.CharField(default='batt1', max_length=30),
        ),
    ]
